sudo: required
services:
- docker
language: c
env:
- BOOTMAKER_ARCH=x86_64
- BOOTMAKER_ARCH=armhf
install:
- sudo apt-get update && sudo apt-get -y install qemu-user-static
- docker run --rm -ti --privileged multiarch/qemu-user-static:register --reset
script:
- BOOTMAKER_ARCH=$BOOTMAKER_ARCH ./build.sh
